all:
  children:
    servers:
      hosts:
        avo:
          ansible_host: 192.168.1.9
          owner: jknetl
    workstations:
      hosts:
        localhost:
          ansible_connection: local
