- name: install k3s cluster
  hosts: servers
  tasks:
    - name: Install microk8s
      become: yes
      become_method: sudo
      block:
       - name: Install microk8s
         shell:  snap install microk8s --classic
       - name: Wait for microk8s startup
         shell: microk8s status --wait-ready
       - name: Enable microk8s services
         shell: microk8s enable dashboard dns registry istio